<a href="https://colab.research.google.com/github/AlejandroVillazonG/ayudantias_MAT281/blob/main/ayudantias_2023/Ayud2_MAT281_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src="https://matematica.usm.cl/wp-content/themes/dmatUSM/assets/img/logoDMAT2.png" title="Title text" width= 800 /></center>
<hr style="height:2px;border:none"/>
<h1 align='center'> Ayudantía 2: Introducción a la librería NumPy</h1>

<H3 align='center'> MAT281 2023-2 </H3>

<H3 align='center'> Ayud. Alejandro Villazón G. </H3>
<hr style="height:2px;border:none"/>

En esta ayudantía introduciremos algunos conceptos de computación cientifica en Python, principalmente utilizando la biblioteca `NumPy`, base de otras librerías científicas.

## SciPy.org

**SciPy** es un ecosistema de software _open-source_ para matemática, ciencia y ingeniería. Las principales bibliotecas son:

* NumPy: Arrays N-dimensionales. Librería base, integración con C/C++ y Fortran.
* SciPy library: Computación científica (integración, optimización, estadística, etc.)
* Matplotlib: Visualización 2D.
* SimPy: Matemática Simbólica.
* Pandas: Estructura y análisis de datos.

## NumPy

NumPy es el paquete fundamental para la computación científica en Python. Proporciona un objeto de matriz multidimensional, varios objetos derivados (como matrices y arreglos) y una variedad de rutinas para operaciones rápidas en matrices, incluida la manipulación matemática, lógica, de formas, clasificación, selección, I/O, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación y mucho más. [Fuente.](https://numpy.org/devdocs/user/whatisnumpy.html)

Para comenzar, la forma usual de importar `NumPy` es utilizando el alias `np`. Lo verás así en una infinidad de ejemplos, libros, blogs, etc.

In [1]:
import numpy as np

### Lo básico

Los objetos principales de Numpy son los comúnmente conocidos como NumPy Arrays (la clase se llama `ndarray`), corresponden a una tabla de elementos, todos del mismo tipo, indexados por una tupla de enteros no-negativos. En NumPy, las dimensiones son llamadas `axes` (ejes) y su singular `axis` (eje), similar a un plano cartesiano generalizado. Esta parte de la ayudantía está basada en el _Quickstart tutorial_ de la página oficial ([link](https://numpy.org/devdocs/user/quickstart.html)).

Instanciar un NumPy Array es simple es utilizando el constructor propio de la biblioteca.

In [2]:
a = np.array([[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14]])

In [3]:
type(a)

numpy.ndarray

Los atributos más importantes de un `ndarray` son:

In [4]:
a.shape  # las dimensiones del array.

(3, 5)

In [5]:
a.ndim  # el número de ejes (dimensiones) del array.

2

In [6]:
a.size  # el número total de elementos en el array.

15

In [7]:
a.dtype  # un objecto describiendo el tipo de los elementos en el array.

dtype('int64')

### [Crear Numpy Arrays](https://numpy.org/doc/stable/reference/routines.array-creation.html)

Hay varias formas de crear arrays, el constructor básico es el que se utilizó hace unos momentos, `np.array`.

El _type_ del array resultante es inferido de los datos proporcionados.

In [8]:
a_int = np.array([4, 6, 10])
a_float = np.array([1.33, 5, 8], )

print(f"a_int: {a_int.dtype}")
print(f"a_float: {a_float.dtype}")

a_int: int64
a_float: float64


In [9]:
a_float

array([1.33, 5.  , 8.  ])

También es posible utilizar otras estructuras de Python, como listas o tuplas.

In [10]:
a_list = [1, 1, 2, 3, 5]
np.array(a_list)

array([1, 1, 2, 3, 5])

In [11]:
list(np.array(a_list))

[1, 1, 2, 3, 5]

In [12]:
a_tuple = (1, 1, 1, 3, 5, 9)
np.array(a_tuple)

array([1, 1, 1, 3, 5, 9])

In [13]:
tuple(np.array(a_tuple))

(1, 1, 1, 3, 5, 9)

__¡Cuidado!__ Es fácil confundirse con las dimensiones o el tipo de argumento en los contructores de NumPy, por ejemplo, utilizando una lista podríamos crear un arreglo de una o dos dimensiones si no tenemos cuidado.

In [14]:
one_dim_array = np.array(a_list)
two_dim_array = np.array([a_list])

print(f"np.array(a_list) = {one_dim_array} tiene shape: {one_dim_array.shape}, es decir, {one_dim_array.ndim} dimensión(es).")
print(f"np.array([a_list]) = {two_dim_array} tiene shape: {two_dim_array.shape}, es decir, {two_dim_array.ndim} dimensión(es).")

np.array(a_list) = [1 1 2 3 5] tiene shape: (5,), es decir, 1 dimensión(es).
np.array([a_list]) = [[1 1 2 3 5]] tiene shape: (1, 5), es decir, 2 dimensión(es).


Una funcionalidad útil son los constructores especiales a partir de constantes.

In [15]:
np.zeros((3, 4), dtype = int)  # el tipo también puede ser especificado

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones((2, 3, 4), dtype=float)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.full((3,2), 99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [18]:
np.identity(4)  # matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.full_like(one_dim_array, 2)

array([2, 2, 2, 2, 2])

Por otro lado, NumPy proporciona una función análoga a `range`.

In [20]:
range(10)

range(0, 10)

In [21]:
type(range(10))

range

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(np.arange(10))

numpy.ndarray

In [24]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2, 20, 3, dtype=float)

array([ 2.,  5.,  8., 11., 14., 17.])

Utilizar `np.arange` tiene como _"ingredientes"_ el inicio (_start_), fin (_stop_) y el tamaño del espacio entre valores (_step_) y el largo (`len`) depende de estos argumentos.

Sin embargo, existe la función `np.linspace` que construye un `np.array` con un inicio y un fin, pero indicando la cantidad de elementos. Está función es muy útil ya que genera puntos equiespaciados.

`np.linspace(a,b,n)` genera `n` puntos equiespaciados en el intervalo cerrado `[a,b]`, con distancia entre puntos: `(b-a)/n`. Por ejemplo,

In [26]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

Esto puede causar confusión, pues recuerda que la indexación de Python (y por lo tanto NumPy) comienza en cero, por lo que si quieres replicar el `np.array` anterior con `np.arange` debes tener esto en consideración. Es decir:

In [27]:
np.arange(start=0, stop=100, step=25)  # stop = 100

array([ 0, 25, 50, 75])

In [28]:
np.arange(start=0, stop=101, step=25)  # stop = 101

array([  0,  25,  50,  75, 100])

También puedes obtener arrays con elementos aleatorios.

In [29]:
np.random.random(size=(3,3))  # Elementos entre 0 y 1

array([[0.55096492, 0.5032505 , 0.32230351],
       [0.74958053, 0.6966525 , 0.13005801],
       [0.43253454, 0.58420632, 0.80549026]])

In [30]:
np.random.randint(low=2, high=99, size=(2,4))

array([[52, 31, 81, 23],
       [26, 78, 34, 22]])

Y desde ciertas distribuciones:

In [31]:
np.random.uniform(low=3, high=7, size=5)  # Desde una distribución uniforme

array([3.89218188, 3.25310212, 5.45818757, 4.9439271 , 4.82965009])

In [32]:
np.random.normal(loc=100, scale=10, size=(2, 3))   # Desde una distribución normal univariada indicando media y desviación estándar

array([[114.61775582, 105.66741391, 100.46064963],
       [ 94.55297458,  86.52609207,  99.47271148]])

In [33]:
np.random.chisquare(df=4, size=(2, 2))

array([[1.56703616, 5.14291417],
       [0.96136401, 2.77536304]])

Dado un array existente, podemos cambiar su dimensión a nuestra conveniencia con el comando `reshape`, solo necesitamos saber la cantidad de elementos del array. Por ejemplo,

In [34]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b = a.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
b.reshape(np.size(b)) #revisar función np.ravel(), np.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.ravel(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Acceder a los elementos de un array

Es muy probable que necesites acceder a elementos o porciones de un array, para ello NumPy tiene una sintáxis consistente con Python.

In [39]:
x1 = np.arange(0, 30, 4)
x2 = np.arange(0, 60, 3).reshape(4, 5)
print(f"{x1=}\n{x2=}")

x1=array([ 0,  4,  8, 12, 16, 20, 24, 28])
x2=array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])


In [40]:
x1[1]  # Un elemento de un array 1D

4

In [41]:
x1[:3]  # Los tres primeros elementos

array([0, 4, 8])

In [42]:
x1[::-1] # En orden inverso

array([28, 24, 20, 16, 12,  8,  4,  0])

Hasta aquí todo bien, los array de una dimensión se comportan como las listas. ¿Y si aumentamos la dimensión?

In [43]:
x2[0,2] #=x2[0][2] # Un elemento de un array 2D

6

In [44]:
x2[0]  # La primera fila

array([ 0,  3,  6,  9, 12])

In [45]:
x2[:, 1]  # Todas las filas y la segunda columna

array([ 3, 18, 33, 48])

In [46]:
x2[:, 1:3]  # Todas las filas y de la segunda a la tercera columna

array([[ 3,  6],
       [18, 21],
       [33, 36],
       [48, 51]])

Nuevamente, recordar que Python tiene indexación partiendo desde cero. Además, la dimensión del arreglo también depende de la forma en que se haga la selección.

In [47]:
x2[:, 2]

array([ 6, 21, 36, 51])

In [48]:
x2[:, 2:3]

array([[ 6],
       [21],
       [36],
       [51]])

En el ejemplo anterior los valores son los mismos, pero las dimensiones no. En el primero se utiliza `indexing` para acceder a la tercera columna, mientras que en el segundo `slicing` para acceder desde la tercera columna a la tercera columna.

In [49]:
print(x2[:, 2].shape)
print(x2[:, 2:3].shape)

(4,)
(4, 1)


### Operaciones Básicas

Una de las grandes utilidades de trabajar con Numpy es que provee operaciones vectorizadas, con tal de mejorar el rendimiento de la ejecución.

Por ejemplo, pensemos en la suma de dos listas.

In [50]:
a = list(range(5))
b = 5*[2]
print(a)
print(b)
print(a+b)

[0, 1, 2, 3, 4]
[2, 2, 2, 2, 2]
[0, 1, 2, 3, 4, 2, 2, 2, 2, 2]


Si quisieramos sumar las listas elemento a elemento no nos sirve la suma de listas. Con los conocimientos repasados en la última ayudantía:

In [51]:
suma_de_listas = lambda a,b : [x+y for x,y in zip(a,b)]
suma_de_listas(a,b)

[2, 3, 4, 5, 6]

Si aumentas la dimesión, aumenta la cantidad de `for`, lo cual a su vez aumenta el tiempo de ejecución. Esto con NumPy no sucede, pues está optimizado:

In [52]:
A = np.arange(5)
B = np.full(5,2)
print(f'{A = }\n{B = }\n{A + B = }')

A = array([0, 1, 2, 3, 4])
B = array([2, 2, 2, 2, 2])
A + B = array([2, 3, 4, 5, 6])


Las clásicas operaciones:

In [53]:
x = np.arange(5)
print(f"{x      = }")
print(f"{x + 5  = }")
print(f"{x - 5  = }")
print(f"{x * 2  = }")
print(f"{x / 2  = }")
print(f"{x // 2 = }")
print(f"{x ** 2 = }")
print(f"{x % 2  = }")

x      = array([0, 1, 2, 3, 4])
x + 5  = array([5, 6, 7, 8, 9])
x - 5  = array([-5, -4, -3, -2, -1])
x * 2  = array([0, 2, 4, 6, 8])
x / 2  = array([0. , 0.5, 1. , 1.5, 2. ])
x // 2 = array([0, 0, 1, 1, 2])
x ** 2 = array([ 0,  1,  4,  9, 16])
x % 2  = array([0, 1, 0, 1, 0])


¡Júntalos como quieras!

In [54]:
-(0.5 + x + 3) ** 2

array([-12.25, -20.25, -30.25, -42.25, -56.25])

Podríamos estar todo el día hablando de operaciones, pero básicamente, si piensas en alguna operación lo suficientemente común, la puedes encontrar implementada en Numpy. Por ejemplo:

In [55]:
np.abs(-(0.5 + x + 3) ** 2)

array([12.25, 20.25, 30.25, 42.25, 56.25])

In [56]:
np.log(x + 5)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [57]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [58]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Para dimensiones mayores la idea es la misma, pero siempre hay que tener cuidado con las dimensiones (`shape`) de los arrays.

In [59]:
A = np.arange(9).reshape((3,3))
B = np.random.randint(7,20,size=(3,3))
print(f'{A=}\n{B=}')

A=array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
B=array([[18,  7, 14],
       [19, 14, 12],
       [ 7, 11, 16]])


In [60]:
print("A + B: \n")
print(A + B)
print("\n" + "-" * 80 + "\n")
print("A - B: \n")
print(A - B)
print("\n" + "-" * 80 + "\n")
print("A * B: \n")
print(A * B)  # Producto elemento a elemento, Hadamard Product busca las propiedades!
print("\n" + "-" * 80 + "\n")
print("A / B: \n")
print(A / B)  # División elemento a elemento
print("\n" + "-" * 80 + "\n")
print("A @ B: \n")
print(A @ B)  # Producto matricial
print("\n" + "-" * 80 + "\n")
print(f'A.T: \n\n{A.T}') # Matriz Transpuesta

A + B: 

[[18  8 16]
 [22 18 17]
 [13 18 24]]

--------------------------------------------------------------------------------

A - B: 

[[-18  -6 -12]
 [-16 -10  -7]
 [ -1  -4  -8]]

--------------------------------------------------------------------------------

A * B: 

[[  0   7  28]
 [ 57  56  60]
 [ 42  77 128]]

--------------------------------------------------------------------------------

A / B: 

[[0.         0.14285714 0.14285714]
 [0.15789474 0.28571429 0.41666667]
 [0.85714286 0.63636364 0.5       ]]

--------------------------------------------------------------------------------

A @ B: 

[[ 33  36  44]
 [165 132 170]
 [297 228 296]]

--------------------------------------------------------------------------------

A.T: 

[[0 3 6]
 [1 4 7]
 [2 5 8]]


### Operaciones Booleanas

In [61]:
print(f"{x      = }")
print(f"{x > 2  = }")
print(f"{x == 2 = }")

x      = array([0, 1, 2, 3, 4])
x > 2  = array([False, False, False,  True,  True])
x == 2 = array([False, False,  True, False, False])


In [62]:
aux1 = np.array([[1, 2, 3], [2, 3, 5], [1, 9, 6]])
aux2 = np.array([[1, 2, 3], [3, 5, 5], [0, 8, 5]])

B1 = aux1 == aux2
B2 = aux1 > aux2

print("B1: \n")
print(B1)
print("\n" + "-" * 80 + "\n")
print("B2: \n")
print(B2)
print("\n" + "-" * 80 + "\n")
print("~B1: \n")
print(~B1)  # También puede ser np.logical_not(B1)
print("\n" + "-" * 80 + "\n")
print("B1 | B2 : \n")
print(B1 | B2)
print("\n" + "-" * 80 + "\n")
print("B1 & B2 : \n")
print(B1 & B2)

B1: 

[[ True  True  True]
 [False False  True]
 [False False False]]

--------------------------------------------------------------------------------

B2: 

[[False False False]
 [False False False]
 [ True  True  True]]

--------------------------------------------------------------------------------

~B1: 

[[False False False]
 [ True  True False]
 [ True  True  True]]

--------------------------------------------------------------------------------

B1 | B2 : 

[[ True  True  True]
 [False False  True]
 [ True  True  True]]

--------------------------------------------------------------------------------

B1 & B2 : 

[[False False False]
 [False False False]
 [False False False]]


### Broadcasting

¿Qué pasa si las dimensiones no coinciden? Observemos lo siguiente:

In [63]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

Todo bien, dos arrays 1D de 3 elementos, la suma retorna un array de 3 elementos.

In [64]:
a + 3

array([3, 4, 5])

Sigue pareciendo normal, un array 1D de 3 elementos, se suma con un `int`, lo que retorna un array 1D de tres elementos.

In [65]:
M = np.ones((3, 3))
print(f'{M = }\n{a = }')

M = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
a = array([0, 1, 2])


In [66]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Magia! Esto es _broadcasting_. Una pequeña infografía para digerirlo:

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

Resumen: A lo menos los dos arrays deben coincidir en una dimensión. Luego, el array de dimensión menor se extiende con tal de ajustarse a las dimensiones del otro.

La documentación oficial de estas reglas la puedes encontrar [aquí](https://numpy.org/devdocs/user/basics.broadcasting.html).

### [Joining Arrays](https://numpy.org/devdocs/reference/routines.array-manipulation.html#joining-arrays)

NumPy ofrece varias funciones para unir o combinar ``arrays`` de diferentes formas y dimensiones (`shape`). Las operaciones de unión más comunes son:

* `np.concatenate`: Esta función se utiliza para concatenar arrays a lo largo de un eje específico. Los arrays deben tener las mismas dimensiones en todos los ejes excepto el eje de concatenación.

In [67]:
arr1 = np.arange(9).reshape(3,3)

arr2 = np.arange(9,18).reshape(3,3)

result = np.concatenate((arr1, arr2), axis = 0)
result

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

* ``np.vstack`` y ``np.hstack``: Estas funciones se utilizan para apilar arrays verticalmente y horizontalmente, respectivamente.

In [68]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_vstack = np.vstack((arr1, arr2))
result_hstack = np.hstack((arr1, arr2))

print("Vertical Stack:")
print(result_vstack)

print("Horizontal Stack:")
print(result_hstack)

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]


* `np.stack`: Esta función apila arrays a lo largo de un nuevo eje, requiere que todos los arrays tengan la misma dimensión.

In [69]:
arr1 = np.arange(9).reshape(3,3)

arr2 = np.arange(9,18).reshape(3,3)

result = np.stack((arr1, arr2), axis=2)
print(result)
result.shape

[[[ 0  9]
  [ 1 10]
  [ 2 11]]

 [[ 3 12]
  [ 4 13]
  [ 5 14]]

 [[ 6 15]
  [ 7 16]
  [ 8 17]]]


(3, 3, 2)

### Extras

En ocasiones nos gustaría aplicar funciones definidas por nosotros a cada elemento de un array para aprovechar la vectorización que nos ofrece NumPy, pero si se involucran condicionales (if, elif, else) puede haber problemas. El siguiente ejemplo lo explica mejor,

In [70]:
f = lambda x: 1 if x > 0.5 else 0 # Decidimos la cara de una moneda
print(f'{f(0.9) = }\n{f(0.1) = }')

f(0.9) = 1
f(0.1) = 0


La operación es sencilla, si el valor es mayor que $0.5$ retorna $1$, en caso contrario retorna $0$. ¿Qué pasa si queremos aplicarselo a un array?

In [71]:
x = np.random.uniform(0,1,100) # 100 realizaciones de una Uniforme[0,1]
f(x)

ValueError: ignored

Podemos usar la función `np.vectorize` que tal como dice su nombre vectoriza una función, lo que soluciona nuestro problema de ambigüedad.

In [72]:
ff = np.vectorize(f)
ff(x)

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0])

Lamentablemente por tiempo no podemos revisar todas las funciones implementadas en NumPy :(

Te invito a que las busques por tu cuenta, revisa la documentación de cada [rutina](https://numpy.org/devdocs/reference/routines.html) para que le saques provecho a todos sus argumentos.

En particular, para otros cursos te puede ser útil el módulo de Álgebra Lineal ([np.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)).    

## Ejercicio

El siguiente ejercicio fue extraído de esta [página](https://www.freecodecamp.org/espanol/learn/data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator).

Crea una función llamada `calculate()` que use lo que hemos aprendido de Numpy para devolver la media, varianza, desviación estándar, máximo, mínimo, y suma de las filas, columnas y elementos en una matriz de 3 x 3.

La entrada de la función debe ser una lista que contenga 9 valores. La función debe convertir la lista en una matriz numérica de 3 x 3, y luego devolver un diccionario que contenga la media, varianza, desviación estándar, máximo, mínimo, y suma a lo largo de ambos ejes y para la matriz aplanada.

El diccionario retornado debería seguir este formato:

```python
{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}
```

Si una lista que contiene menos de 9 elementos es pasada a la función, debería levantar una excepción de ValueError con el mensaje: "La lista debe contener nueve números". Los valores en el diccionario devuelto deben ser listas y no matrices Numpy.

Por ejemplo, ``calculate([0,1,2,3,4,5,6,7,8])`` debe regresar:

```python
{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0],
               [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
                6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178],
                         [0.816496580927726, 0.816496580927726, 0.816496580927726],
                          2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}
```
Te puede ser útil visitar estos links: [averages-and-variances](https://numpy.org/devdocs/reference/routines.statistics.html#averages-and-variances), [extrema-finding](https://numpy.org/devdocs/reference/routines.math.html#extrema-finding) y [sums-products-differences](https://numpy.org/devdocs/reference/routines.math.html#sums-products-differences).

In [ ]:
# COMPLETA EL CÓDIGO

def calculate():
    if ???:
        raise ValueError(???)

    ???

    return ???

In [74]:
def calculate(lista):
    if len(lista) < 9:
        raise ValueError('List must contain nine numbers.')
    array = np.array(lista).reshape((3,3))
    dicc = {'mean' : [list(array.mean(axis=0)),list(array.mean(axis=1)),array.mean()],
            'variance': [list(array.var(axis=0)),list(array.var(axis=1)),array.var()],
            'standard deviation': [list(array.std(axis=0)),list(array.std(axis=1)),array.std()],
            'max': [list(array.max(axis=0)),list(array.max(axis=1)),array.max()],
            'min': [list(array.min(axis=0)),list(array.min(axis=1)),array.min()],
            'sum': [list(array.sum(axis=0)),list(array.sum(axis=1)),array.sum()]
            }
    return dicc

Compara tus resultados.

<!--
ValueError, Exception, TypeError, SyntaxError
 -->

In [75]:
calculate([0,1,2,3,4,5,6,7,8])

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

Aquí tienes otro ejemplos para que compares ;)

> `calculate([1,2])`

```python
ValueError: List must contain nine numbers.
```

In [76]:
calculate([1,2])

ValueError: ignored

> ``calculate([2,6,2,8,4,0,1,5,7])``

```python
{
    'mean': [[3.6666666666666665, 5.0, 3.0],
             [3.3333333333333335, 4.0, 4.333333333333333],
              3.888888888888889],
    'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
                 [3.555555555555556, 10.666666666666666, 6.222222222222221],
                  6.987654320987654],
    'standard deviation': [[3.091206165165235, 0.816496580927726, 2.943920288775949],
                           [1.8856180831641267, 3.265986323710904, 2.494438257849294],
                            2.6434171674156266],
    'max': [[8, 6, 7], [6, 8, 7], 8],
    'min': [[1, 4, 0], [2, 0, 1], 0],
    'sum': [[11, 15, 9], [10, 12, 13], 35]
}
```

In [77]:
calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

> ``calculate([9,1,5,3,3,3,2,9,0])``
```python
{
    'mean': [[4.666666666666667, 4.333333333333333, 2.6666666666666665],
             [5.0, 3.0, 3.6666666666666665],
              3.888888888888889],
    'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222],
                 [10.666666666666666, 0.0, 14.888888888888891],
                  9.209876543209875],
    'standard deviation': [[3.0912061651652345, 3.39934634239519, 2.0548046676563256],
                           [3.265986323710904, 0.0, 3.8586123009300755],
                            3.0347778408328137],
  'max': [[9, 9, 5], [9, 3, 9], 9],
  'min': [[2, 1, 0], [1, 3, 0], 0],
  'sum': [[14, 13, 8], [15, 9, 11], 35]
}
```

In [78]:
calculate([9,1,5,3,3,3,2,9,0])

{'mean': [[4.666666666666667, 4.333333333333333, 2.6666666666666665],
  [5.0, 3.0, 3.6666666666666665],
  3.888888888888889],
 'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222],
  [10.666666666666666, 0.0, 14.888888888888891],
  9.209876543209875],
 'standard deviation': [[3.0912061651652345,
   3.39934634239519,
   2.0548046676563256],
  [3.265986323710904, 0.0, 3.8586123009300755],
  3.0347778408328137],
 'max': [[9, 9, 5], [9, 3, 9], 9],
 'min': [[2, 1, 0], [1, 3, 0], 0],
 'sum': [[14, 13, 8], [15, 9, 11], 35]}